#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

class CameraSubscriber(Node):
    def __init__(self):
        super().__init__('camera_node')
        self.get_logger().info('Camera node started')
        self.bridge = CvBridge()
        # Tworzymy subskrybenta na temat /image_raw
        self.subscription = self.create_subscription(
            Image,
            '/image_raw',
            self.listener_callback,
            10
        )
        self.subscription  # aby uniknąć “unused variable warning”

    def listener_callback(self, image_data):
        # Konwersja ROS Image → OpenCV
        cv_image = self.bridge.imgmsg_to_cv2(image_data, 'bgr8')
        # Wyświetlanie obrazu
        cv2.imshow("camera", cv_image)
        cv2.waitKey(1)

def main(args=None):
    rclpy.init(args=args)
    node = CameraSubscriber()
    rclpy.spin(node)
    rclpy.shutdown()

if __name__ == '__main__':
    main()

