#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from geometry_msgs.msg import Point
import cv2
import numpy as np


class MinimalSubscriber(Node):
    def __init__(self):
        super().__init__('minimal_subscriber')

        self.window_name = "camera"

        # PARAMETR ROS 2
        self.declare_parameter('square_size', 200)
        self.square_size = self.get_parameter('square_size').value

        self.get_logger().info(
            f'Square size parameter set to: {self.square_size}'
        )

        # Publisher Point
        self.publisher_ = self.create_publisher(Point, '/point', 10)

        # Timer (bez kamery)
        self.timer = self.create_timer(0.05, self.timer_callback)
        cv2.namedWindow(self.window_name)

        self.point = None

    def timer_callback(self):
        cv_image = np.zeros((512, 700, 3), np.uint8)

        if self.point is not None:
            cv2.rectangle(
                cv_image,
                self.point,
                (
                    self.point[0] + self.square_size,
                    self.point[1] + self.square_size
                ),
                (0, 255, 0),
                3
            )

        cv2.imshow(self.window_name, cv_image)
        cv2.waitKey(1)
        cv2.setMouseCallback(self.window_name, self.draw_rectangle)

    def draw_rectangle(self, event, x, y, flags, param):
        if event == cv2.EVENT_LBUTTONDOWN:
            self.point = (x, y)

            msg = Point()
            msg.x = float(x)
            msg.y = float(y)
            msg.z = 0.0

            self.publisher_.publish(msg)

            self.get_logger().info(
                f'Published Point: x={msg.x}, y={msg.y}, z={msg.z}'
            )


def main(args=None):
    rclpy.init(args=args)
    node = MinimalSubscriber()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()

