#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist


class CmdVelPublisher(Node):
    def __init__(self):
        super().__init__('cmd_vel_publisher')

        # Publisher na /cmd_vel
        self.publisher_ = self.create_publisher(Twist, '/cmd_vel', 10)

        # Timer (10 Hz)
        self.timer = self.create_timer(0.1, self.timer_callback)

        self.get_logger().info('Cmd_vel publisher started')

    def timer_callback(self):
        msg = Twist()

        # Robot obraca się w miejscu
        msg.linear.x = 0.0
        msg.angular.z = 0.5  # prędkość kątowa (rad/s)

        self.publisher_.publish(msg)

        self.get_logger().info(
            f'Publishing cmd_vel: angular.z = {msg.angular.z}'
        )


def main(args=None):
    rclpy.init(args=args)
    node = CmdVelPublisher()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
